import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div className="px-12">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen py-24 flex-1">
        <h1 className="flex flex-1 py-4 border-t border-t-gray-100 justify-center items-center text-4xl font-bold">
          Welcome to &nbsp;
          <a href="https://nextjs.org" className="!text-blue-500">
            Next.js
          </a>
        </h1>
      </main>
    </div>
  );
};

export default Home;
